### ISSUE TITLE
Can't start application

### ISSUE THREAD

**Issue by stojankukrika** [bestmomo/lumenvue#1]
Hi,
I find this tutorial project and can't start it on localhost. In every route as '/' i get a error:
http://view.xscreenshot.com/fea5a2c4868e6296a8570d526e7b2d83
I follow install instructions and install it correctly with populate database using seeds. But I do not know hot to solve this problem. Can you help me?

**Comment by bestmomo** [comment]
Hi,
You must have a virtual host in local to make it work.

**Comment by stojankukrika** [comment]
How I can start it in localhost?And what ai need to change to start it in localhost?

**Comment by stevepop** [comment]
@stojankukrika did you run `php artisan serve?` 
This should run in development mode and works perfectly on port 8000.

**Comment by stojankukrika** [comment]
👍 tnx
